services: 

  db: 
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: password

    

  backend: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9292:9292"
    volumes:
      - .:/STAY-VIBES
    environment:
      - DB_HOST=db
      - RACK_ENV=development
    depends_on: 
      - db


  frontend:
      build: 
        context: client
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      environment:
          - NODE_ENV=development

    

